### PR TITLE
A candidate fix for #6 - Postmeta storage

### PR DESCRIPTION
**Pull request by ideag**
A candidate fix for #6:
- stores OG data in postmeta
- updates OG data via WP_Cron
- update interval can be tweaked in Options
- removes OG data for links that were removed from `post_content`

Thoughts, @khromov ?

I only see one performance bottleneck now - the initial request for OG data still happens on the first pageview, not in the editor/via cron, if link is inserted via shortcode. It is not a big problem if request is successful, as then it happens only once. But if request fails (bad link, bad connection, remote server down, no OG tags in remote site etc.), Content Cards would try again (on every pageview), until it succeeds. Maybe some kind of throttling should be added for this case?

### CODE REVIEW

**Comment by khromov** [comment]
We can get around the whole "first load" problem by creating a preview in the TinyMCE editor. The oEmbed URL:s actually already are previewed in the TinyMCE editor, try adding it via Add Media > Insert From URL. (Must be whitelisted oEmbed URL).

Here is an example:
wordpress-preview

Example shows oEmbed first, then shortcode. Since oEmbed gets loaded into the TinyMCE preview we already have the OG data, woo!

So, either we implement it from scratch like this:
http://www.wpsites.co.uk/435-replacing-inserted-shortcodes-in-tinymce-with-a-graphic.php

(Not sure how fresh that example is though)

..or we can also add support for the Shortcake plugin, which is just a few lines of code to implement. 
https://wordpress.org/plugins/shortcode-ui/

Shortcake already has built-in functions for previewing shortcodes in TinyMCE.

Thoughts?

**Comment by ideag** [comment]
The way I see it, its not a _first load_ problem, but rather _what if first load fails_. If we can get the initial OG data in the first load, or at least in second/third try, there is not much of a problem, as this would affect only a few initial pageviews. The problem is if the link _continues_ to be unreachable for a long time. It might be due to user error (using a bad link), an overeager remote firewall, network problems, etc. but in that case all the pageviews of that particular post would become slow.
I could solve this by adding a timeout period before Content Cards try to get OG data again if the initial load fails, but if a problem was a temporary one, user would still have to wait before the card showed up.

**Comment by khromov** [comment]
How about if we fail on the first try, we'll re-queue it to be done by hourly CRON, and until then we show a placeholder such as this:

contant-card-processing

(Just a quick sketch, we'd do it with some better placeholder art.)

We could even limit the number of re-tries, and if for example it fails 5x times, we can change the placeholder to an error. However, I'm not sure it's good to show an error on the frontend...

Thoughts @ideag ?

**Comment by ideag** [comment]
@khromov yeah, probably something like that. I am thinking of progression like this:
1. Merging this PR _as is_.
2. Implementing shortcode preview in TinyMCE (I found the code in Core for `[gallery]` shortcode preview, should be able to adapt it nicely.)
3. In case of error, show a notice instead of preview in Editor, and show plain link in frontend; 
4. Schedule some retries via `WP_Cron`. I am thinking thirst retry after 1 minute, 2nd - after 5 more minutes, and then double the timeout for every other retry.

**Comment by khromov** [comment]
@ideag Sounds great. I like the idea of showing just a simple text link, although we need to indicate to the user somehow that we are trying to process his link in the background.

A related topic, if the site does not have OG, maybe we should fall back to use the `<title>` tag and the `<meta name="description">` tag for description text if it exists? Would make this work fairly ok on most sites even if they don't implement OG.

**Pull request merged**
