### PR TITLE
Add filterable CSS classes

### PR DESCRIPTION
**Pull request by khromov**
Introduces the `content_cards_css_classes` filter.

As per:
https://wordpress.org/support/topic/mult-columnar-layout?replies=2

### CODE REVIEW

**Comment by ideag** [comment]
@khromov I added the possibility to set CSS classes via shortcode attribute to. I think that would make sense if you want to add some styling to just some of the cards, not all of them.

**Comment by khromov** [comment]
@ideag Would a normal user ever add classes? I believe 99.9% of users would not use that feature.

I also can't imagine why some cards would look different than others. Even if you wanted that  it's easily doable with the filter. (Although we should maybe pass all the OG data to the `content_cards_css_classes` filter so it can be used in making a decision for which class to use.)

But adding a class selector to the TinyMCE modal seems like unnecessary bloat. :-1:

**Comment by ideag** [comment]
@khromov I'd say that number would be closer to 98%. But some power users might find it useful. 

I.E. some themes have a wide (no sidebar) template for a page. User might want to put two cards next to one another on such page, but keep single column layout on other pages. Or if user has several content cards on page, they might want to make one to stand out even more (red background, etc.). I can think of several use cases for this. 

Of course, power users should be able to set a `class=""`attribute by hand, so we might leave it out of the modal dialog.

**Comment by khromov** [comment]
@ideag Great points, fully agree.

How about hiding the link target and class options under an "Advanced options" dropdown? That way we streamline the experience for most users.

Something like this? 

screen shot 2015-09-15 at 16 11 44
(Warning: Super quick sketch done via web inspector :smile: )

**Comment by ideag** [comment]
Nice idea, I'll have to look into what the api of those modals is capable of :) :+1: 

P.S. The same reasoning goes for allowing custom word_limit in shortcodes ( #62 )

**Comment by khromov** [comment]
@ideag Great, and yes, absolutely. We should try to represent all shortcode options under the advanced options dialogue. :smile:

**Comment by ideag** [comment]
@khromov actually, that collapsable panel is not so easy to implement in tinyMCE. Or at least documentation is really hard to find. I came up with a solution using tabs instead:

main tab
advanced tab

What do you think?

**Comment by khromov** [comment]
Looks great! :+1:

**Comment by ideag** [comment]
- The new, multi tab dialog for adding/editing shortcodes.
- Refactored `build()` method to allow more stuff set up via shortcode/filters
- added `content_cards_args` filter, that will allow to modify Content Card options dynamically, on card-by-card basis.
  This also fixes #62 and the `chetan.g` problem from wp.org

**Comment by khromov** [comment]
Very clean code, A++ would read again. :smile:

**Pull request merged**
