### PR TITLE
Better branding

### PR DESCRIPTION
**Pull request by khromov**
The icon is good but I don't think we're explaining **what** Content Cards are very well in the banner.

With this change, we'll make it abundantly clear that Content Cards = beautiful embeds.

### CODE REVIEW

**Comment by khromov** [comment]
Another suggestion for the banner:

banner-772x250

**Comment by ideag** [comment]
@khromov so, I tested out the branding on some of my students and a colleague who teaches Graphic Design. Here is what they had to say.

**Students**. Banner was 50-50, but they voted for the cleaner icon pretty much unanimously.

**Design Teacher**. In her opinion the new banner is a bit unbalanced with everything happening on the sides and nothing in the middle. If we go on with this kind of design, there is a need of some graphical element in the middle to connect the logo and the stack. Like a line of dots or something.
For the icon, the one with the stack feels 'cramped' and in small version, like how it shows up in plugin directory, it just isn't readable/recognizable enough. She also recommends the clean icon.

**Comment by khromov** [comment]
@ideag 
Good feedback.

Did you show the banner with the "Content Cards" text in the bottom left? Because without it, it may seem a bit unbalanced, but if you include the text it feels a bit more well-rounded imho:

banner-772x250

I'll see about trying to connect it better...

**Comment by ideag** [comment]
Yeah, I did show it with the name. her main concern is that the spacing in the middle betweeb objects is way bigger than spacing to the edges. Her words - „everything seems to be falling away to the sides“

**Comment by khromov** [comment]
@ideag I'll show it to some UX folks at work and get some inspiration. :smile: 
to be continued!

**Comment by khromov** [comment]
@ideag New banner design based on feedback:

banner-772x250
- The images in each content card is slightly more cropped. This lets us zoom in and let them take up more of the banner, reducing the whitespace.
- Logo is centered to reduce whitespace.

I think we also agreed to keep the icons as-is, so they have been restored. Ready to merge.

**Pull request merged**
