### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by khromov**
Looked over the readme and tried to clarify some section a bit. Feedback appreciated.

### CODE REVIEW

**Comment by ideag** [comment]
Nice work, @khromov!

Found a small typo ( `t` instead of `T`), but otherwise it looks good. 

Just a note for the future - could we contain readme updates to a separate branch from all other code changes? This is because readme.txt gets updated on WP.org whenever it gets updated in master here. So if I merge some branch to master with changes in readme.txt, the chages go directly to wp.org.

If we keep all changes to readme.txt in a separate branch, I can merge it at the same time I am releasing a new version. 

This was a problem because you documented the new `content_cards_options` filter in the readme and that change showed up on wp.org before we actually released 0.9.4 with the filter.

**Comment by khromov** [comment]
@ideag Sure, we could do that if you prefer it. The optimal thing would maybe be to update the readme only when we tag a release on GitHub? Would that be possible?

**Comment by ideag** [comment]
@khromov well, I actually implemented the continuous update of `readme.txt` because quite often we really do need to modify it separately from new version releases - like when WordPress releases a new version and we need to change compatibility number. Or add/fix/clarify some copy in the description/faq/etc,

It's just the changes that are relevant for the upcoming release that should go into separate branch.

**Comment by khromov** [comment]
Ah, I understand. That's fine!

**Pull request closed without merging**
